print("*** BIODATA MAHASISWA ***")
print("Nama    : Defran Naufalanski")
print("NIM     : 2611532020")
print("Jurusan : Informatika")
print("Kelas   : IF B")
print("Hobi    : Menggambar\n\n")

print("    /\\    ")
print("   /  \\   ")
print("  / /\\ \\  ")
print(" / /  \\ \\ ")
print("/_/_/\\_\\_\\")
print("    ||    ")
print("    ||    ")